version: 2
jobs:
  build:
    docker:
    - image: circleci/ruby:2.6.3-node-browsers
      environment:
        BUNDLER_VERSION: 2.0.1
    steps:
    - checkout
    - run: sudo apt-get update
    - run:
        name: install dependencies
        command: |
          gem update --system
          gem install bundler
    - restore_cache:
        keys:
        - gem-cache-v1-{{ arch }}-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
        - gem-cache-v1-{{ arch }}-{{ .Branch }}
        - gem-cache-v1
    - run: bundle install
    - save_cache:
        key: gem-cache-v1-{{ arch }}-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
        paths:
        - vendor/bundle
    environment:
    - CIRCLE_COMPARE_URL: https://github.com/brianoh1979/sample_app/compare/aec2a071d73b0e48196ec886588563f08d1f6860...aec2a071d73b0e48196ec886588563f08d1f6860
  unittest:
    docker:
    - image: circleci/ruby:2.6.3-node-browsers
      environment:
        BUNDLER_VERSION: 2.0.1
    parallelism: 4
    steps:
    - checkout
    - restore_cache:
        keys:
        - gem-cache-v1-{{ arch }}-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
        - gem-cache-v1-{{ arch }}-{{ .Branch }}
        - gem-cache-v1
    - run: gem install bundler:2.0.1
    - run: bundle update --bundler
    - run: rake db:test:prepare
    - run:
        command: "echo $(circleci tests glob \"spec/features/models/*.rb\") \ncircleci tests glob \"spec/features/models/*.rb\" | xargs -n 1 echo           \n"
    - run: TESTFILES=$(circleci tests glob "spec/features/models/*.rb" | circleci tests split --split-by=filesize)
    - run: echo $TESTFILES
    - run: bundle exec rspec -- ${TESTFILES}
    environment:
    - CIRCLE_COMPARE_URL: https://github.com/brianoh1979/sample_app/compare/aec2a071d73b0e48196ec886588563f08d1f6860...aec2a071d73b0e48196ec886588563f08d1f6860
  browsertest:
    docker:
    - image: circleci/ruby:2.6.3-node-browsers
      environment:
        BUNDLER_VERSION: 2.0.1
    steps:
    - checkout
    - restore_cache:
        keys:
        - gem-cache-v1-{{ arch }}-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
        - gem-cache-v1-{{ arch }}-{{ .Branch }}
        - gem-cache-v1
    - run: sudo apt-get update
    - run:
        name: Install Cypress dependencies
        command: sudo apt-get install xvfb libgtk-3-dev libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 --fix-missing
    - run:
        name: install cypress
        command: npm install cypress --save-dev
    - run: gem install bundler:2.0.1
    - run: bundle update --bundler
    - run:
        name: Boot rails server
        command: bin/rails s
        background: true
    - run: mkdir /tmp/results
    - run: npm install --save-dev mocha mochawesome mochawesome-merge mochawesome-report-generator
    - run:
        name: run
        command: $(npm bin)/cypress run -- --record --spec "cypress/integration/sample_spec.js"
    - store_test_results:
        path: /tmp/results
    - store_artifacts:
        path: /tmp/results
        destination: results
    environment:
    - CIRCLE_COMPARE_URL: https://github.com/brianoh1979/sample_app/compare/aec2a071d73b0e48196ec886588563f08d1f6860...aec2a071d73b0e48196ec886588563f08d1f6860
  lintertest:
    docker:
    - image: circleci/ruby:2.6.3-node-browsers
      environment:
        BUNDLER_VERSION: 2.0.1
    steps:
    - checkout
    - restore_cache:
        keys:
        - gem-cache-v1-{{ arch }}-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
        - gem-cache-v1-{{ arch }}-{{ .Branch }}
        - gem-cache-v1
    - run: gem install bundler:2.0.1
    - run: bundle update --bundler
    - run: bundle-audit check --ignore CVE-2015-7580 CVE-2015-7578 CVE-2015-7579
    - run: rails_best_practices .
    environment:
    - CIRCLE_COMPARE_URL: https://github.com/brianoh1979/sample_app/compare/aec2a071d73b0e48196ec886588563f08d1f6860...aec2a071d73b0e48196ec886588563f08d1f6860
  codecoveragetest:
    docker:
    - image: circleci/ruby:2.6.3-node-browsers
      environment:
        BUNDLER_VERSION: 2.0.1
    steps:
    - checkout
    - restore_cache:
        keys:
        - gem-cache-v1-{{ arch }}-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
        - gem-cache-v1-{{ arch }}-{{ .Branch }}
        - gem-cache-v1
    - run: gem install bundler:2.0.1
    - run: bundle update --bundler
    - run: rake db:test:prepare
    - run: rails test
    - store_artifacts:
        path: coverage
        prefix: coverage
    environment:
    - CIRCLE_COMPARE_URL: https://github.com/brianoh1979/sample_app/compare/aec2a071d73b0e48196ec886588563f08d1f6860...aec2a071d73b0e48196ec886588563f08d1f6860
  deploy:
    docker:
    - image: circleci/ruby:2.6.3-node-browsers
      environment:
        BUNDLER_VERSION: 2.0.1
    steps:
    - checkout
    - restore_cache:
        keys:
        - gem-cache-v1-{{ arch }}-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
        - gem-cache-v1-{{ arch }}-{{ .Branch }}
        - gem-cache-v1
    - run:
        name: Deploy Develop to Heroku
        command: |
          git push --force https://heroku:$HEROKU_API_KEY2@git.heroku.com/thawing-cliffs-50633.git master
    environment:
    - CIRCLE_COMPARE_URL: https://github.com/brianoh1979/sample_app/compare/aec2a071d73b0e48196ec886588563f08d1f6860...aec2a071d73b0e48196ec886588563f08d1f6860
workflows:
  version: 2
  build_and_test:
    jobs:
    - build
    - unittest:
        requires:
        - build
    - browsertest:
        requires:
        - build
    - lintertest:
        requires:
        - build
    - codecoveragetest:
        requires:
        - build
    - deploy:
        requires:
        - unittest
        - browsertest
        - lintertest
        - codecoveragetest
