#This is my config file for CircleCI
 version: 2.0
 jobs:
   build:
     docker:
       - image: circleci/ruby:2.6.3-node-browsers
         environment:
           BUNDLER_VERSION: 2.0.1
     #parallelism: 4
     #Above runs the tests across four containers instead of one
     steps:
       - checkout
       - run: sudo apt-get update
       - run: echo ${CIRCLE_NODE_TOTAL}
       - run: echo ${CIRCLE_SHA1}
       - deploy:
           name: conditionally run a deploy job
           command: |
            # replace this with your build/deploy check (i.e. current branch is "release")
            # if [[ $CIRCLE_BRANCH = "develop" ]]; then
             #  curl --user ${CIRCLE_API_USER_TOKEN}: --request GET https://circleci.com/api/v1.1/project/github/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME/$CIRCLE_BUILD_NUM | jq '.["workflows"]["workflow_id"]'
             verdict=$(curl --user ${CIRCLE_API_USER_TOKEN}: --request GET https://circleci.com/api/v1.1/project/github/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME/$CIRCLE_BUILD_NUM)
             echo $verdict
             verdict2=$(echo $verdict | jq '.["is_first_green_build"]') 
             echo $verdict2
             if [[ $verdict2 == *false* ]]; then
               echo "This is not the first successful run"
             else
               echo "This is the first successful run"
               fi

           #  fi
#       - deploy:
#           name: conditionally run another job
#           command: |
#             echo $verdict2
#             if [[ $verdict2 == *false* ]]; then
#               echo "This is not the first successful run"
#             else
#               echo "This is the first successful run"
#               fi
  #     - run: exit 0
  #     - slack/notify:
  #         channel: CQ4NHT0DC
  #         color: '#42e2f4'
  #         message: This is a custom orb message notification that job worked
  #         webhook: '${SLACK_WEBHOOK}'
# orbs:
#   slack: circleci/slack@3.4.1
# version: 2.1

# orbs:
#   slack: circleci/slack@3.4.1
# version: 2.1
     
 workflows:
   version: 2
   build_and_test:
     jobs:
       - build

