#This is my config file for CircleCI
 version: 2
 jobs:
   build:
     docker:
       - image: circleci/ruby:2.6.3-node-browsers
         environment:
           BUNDLER_VERSION: 2.0.1
     #parallelism: 4
     #Above runs the tests across four containers instead of one
     steps:
       - checkout
 #      - run:
 #          name: Deploy Master to Heroku
 #          command: |
 #            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/thawing-cliffs-50633.git master
 #            curl -v -X POST https://circleci.com/api/v1/project/templth/restlet-client-circleci/tree/master?circle-token=$CIRCLE_TOKEN      
 
       - deploy:
           name: conditionally run a deploy job
           command: |
            # replace this with your build/deploy check (i.e. current branch is "release")
             if [[ $CIRCLE_BRANCH = "develop" ]]; then
               curl --user ${CIRCLE_API_USER_TOKEN}: \
                 --data build_parameters[CIRCLE_JOB]=deploy_docker \
                 --data revision=$CIRCLE_SHA1 \
                 https://circleci.com/api/v1.1/project/github/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME/tree/$CIRCLE_BRANCH
             fi

   deploy_docker:
     docker:
       - image: circleci/ruby:2.6.3-node-browsers
         environment:
           BUNDLER_VERSION: 2.0.1
     steps:
     - run: 
        name: Check if website returns a 500
        command: | 
          response=$(curl -Is https://thawing-cliffs-50633.herokuapp.com/brian | head -1)
          ${response}
          if [ "${response}" == "HTTP/1.1 200 OK" ]; then 
          echo "Website can be reached"
          else 
          echo "Website is returning a 500"
          fi
#     - run: curl -X https://thawing-cliffs-50633.herokuapp.com 

 workflows:
   version: 2
   build_and_test:
     jobs:
       - build

