#This is my config file for CircleCI
# version: 2.1
 jobs:
   build:
     docker:
       - image: circleci/ruby:2.6.3-node-browsers
         environment:
           BUNDLER_VERSION: 2.0.1
     #parallelism: 4
     #Above runs the tests across four containers instead of one
     steps:
       - checkout
       - run: sudo apt-get update
       - run: exit 0
       - slack/status:
           fail_only: true
           mentions: 'USERID1,USERID2'
           only_for_branches: only_for_branches
           webhook: webhook

# orbs:
#   slack: circleci/slack@3.4.1
# version: 2.1

 orbs:
   slack: circleci/slack@3.4.1
 version: 2.1
     
 workflows:
   version: 2
   build_and_test:
     jobs:
       - build

