 version: 2
 jobs:
   build:
     docker:
       - image: circleci/ruby:2.6.3-node-browsers
         environment:
           BUNDLER_VERSION: 2.0.1
     steps:
       - checkout
       - run: sudo apt-get update
       - deploy:
           name: conditionally run a deploy job
           command: |
            # replace this with your build/deploy check (i.e. current branch is "release")
             if [[ $CIRCLE_BRANCH = "develop" ]]; then
               curl --user ${CIRCLE_API_USER_TOKEN}: \
                 --data revision=$CIRCLE_SHA1 \
                 https://circleci.com/api/v2/insights/gh/brianoh1979/mikita_repo/workflows  
             fi
     
 workflows:
   version: 2
   build_and_test:
     jobs:
       - build

