 version: 2
 jobs:
   build:
     docker:
       - image: circleci/ruby:2.6.3-node
     steps:
       - checkout
       - run: sudo apt-get update
       - run:
          name: Install Cypress dependencies
          command: sudo apt-get install xvfb libgtk-3-dev libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 --fix-missing
       - run:
          name: install cypress
          command: npm install cypress --save-dev
       - run:
          name: install dependencies
          command: |
            gem update --system
            gem install bundler

       # Below step should kick in from second run onwards
       - restore_cache:
          keys:
            - gem-cache-v1-{{ arch }}-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
            - gem-cache-v1-{{ arch }}-{{ .Branch }}
            - gem-cache-v1
 #      - run:
 #         name: install-npm-wee
 #         command: npm install
 #      - run: bundle update rails
       - run: bundle install     
 #      - run: bundle update --bundler
 #      - run: bundle install --path vendor/bundle

       - save_cache:
          key: gem-cache-v1-{{ arch }}-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
       - run: rails server --port 3000 --binding 0.0.0.0 | 2>&1 &
       - run: netstat -an | grep "3000"
       - run: ps -ef | grep puma
     #  - run: fasterer
     #  - run: rubocop
       - run: bundle-audit check --ignore CVE-2015-7580 CVE-2015-7578 CVE-2015-7579
       - run: rails_best_practices .
       - run: rails test
       - run: # open cypress and use sample_spec.js
          name: run
          command: $(npm bin)/cypress run -- --record --spec "cypress/integration/sample_spec.js"
     #  - run: # run coverage report
     #     name: code-coverage
     #     command: './node_modules/.bin/nyc report --reporter=text-lcov'
       - store_artifacts: # special step to save test results as as artifact
          # Upload test summary for display in Artifacts: https://circleci.com/docs/2.0/artifacts/ 
          path: /home/circleci/project/cypress/videos/examples/*
          destination: coverage 
       - store_artifacts: # for display in Artifacts: https://circleci.com/docs/2.0/artifacts/ 
          path: coverage
          prefix: coverage
    #   - store_test_results: # for display in Test Summary: https://circleci.com/docs/2.0/collect-test-data/
    #      path: test-results.xml
       # See https://circleci.com/docs/2.0/deployment-integrations/ for deploy examples
    
       
     

