#This is my config file for CircleCI
 # version: 2.1
 jobs:
   build:
     docker:
       - image: circleci/ruby:2.6.3-node-browsers
         environment:
           BUNDLER_VERSION: 2.0.1
     #parallelism: 4
     #Above runs the tests across four containers instead of one
     steps:
       - checkout
       - run: sudo apt-get update
  #     - run: exit 0
       - slack/notify:
           channel: CQ4NHT0DC
           color: '#42e2f4'
           message: Please click on the following link and approve the on-hold jobs - $CIRCLE_BUILD_URL/workflows/CIRCLE_WORKFLOW_ID/jobs
           webhook: '${SLACK_WEBHOOK}'
# orbs:
#   slack: circleci/slack@3.4.1
# version: 2.1

 orbs:
   slack: circleci/slack@3.4.1
 version: 2.1
     
 workflows:
   version: 2
   build_and_test:
     jobs:
       - build

