#This is my config file for CircleCI
# version: 2.1
 jobs:
   build:
     docker:
       - image: circleci/ruby:2.6.3-node-browsers
         environment:
           BUNDLER_VERSION: 2.0.1
     #parallelism: 4
     #Above runs the tests across four containers instead of one
     steps:
       - checkout
 
       - deploy:
           name: conditionally run a deploy job
           command: |
            # replace this with your build/deploy check (i.e. current branch is "release")
             if [[ $CIRCLE_BRANCH = "develop" ]]; then
               curl --user ${CIRCLE_API_USER_TOKEN}: \
                 --data build_parameters[CIRCLE_JOB]=deploy_docker \
                 --data revision=$CIRCLE_SHA1 \
                 https://circleci.com/api/v1.1/project/github/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME/tree/$CIRCLE_BRANCH
             fi

   deploy_docker:
     docker:
       - image: circleci/ruby:2.6.3-node-browsers
         environment:
           BUNDLER_VERSION: 2.0.1

     steps:
     - run: 
        name: Check if website returns a 500
        command: | 
          response=$(curl -Is https://thawing-cliffs-50633.herokuapp.com/brian | head -1)
          echo ${response}
          if [[ ${response} == *200* ]]; then 
          echo "Website can be reached"
          else 
          echo "Website is returning a 500"
          fi
      
     - run: exit 0
     - slack/status:
         fail_only: true
         mentions: 'USERID1,USERID2'
         only_for_branches: only_for_branches
         webhook: webhook
 orbs:
   slack: circleci/slack@3.4.1
 version: 2.1

 workflows:
   version: 2
   build_and_test:
     jobs:
       - build

