#This is my config file for CircleCI
 version: 2.1

 orbs:
   ruby: circleci/ruby@1.1.2
   cypress: cypress-io/cypress@1.26.0
   ruby-linter: amyroi/ruby-linter@1.0.0

 jobs:
   build:
     machine: true
     resource_class: brianoh1979/brian-runner
     #parallelism: 4
     #Above runs the tests across four containers instead of one
     steps:
       - checkout
       - run: bundle init
#       - run: apt-get update
#       - run:
#          name: install dependencies
#          command: |
#            gem update --system
#            gem install bundler
       # Below step should kick in from second run onwards
       - restore_cache:
          keys:
            - gem-cache-v1-{{ arch }}-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
            - gem-cache-v1-{{ arch }}-{{ .Branch }}
            - gem-cache-v1
       - run: bundle install     
       - save_cache:
          key: gem-cache-v1-{{ arch }}-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
          paths:
          - vendor/bundle
   #Start of the Unit Testing
   unittest:
     machine: true
     resource_class: brianoh1979/brian-runner
     parallelism: 4
     #Above runs the tests across four containers instead of one
     steps:
       - checkout
       - ruby/rspec-test
#       - restore_cache:
#          keys:
#            - gem-cache-v1-{{ arch }}-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
#            - gem-cache-v1-{{ arch }}-{{ .Branch }}
#            - gem-cache-v1
#       - run: gem install bundler:2.0.1
#       - run: bundle init
#       - run: bundle update --bundler
#       - run: bundle install
#       - run: rake db:test:prepare 
#       - run:
#           command: |
#             echo $(circleci tests glob "spec/features/models/*.rb") 
#             circleci tests glob "spec/features/models/*.rb" | xargs -n 1 echo           
#       - run: TESTFILES=$(circleci tests glob "spec/features/models/*.rb" | circleci tests split --split-by=filesize)
#       - run: echo $TESTFILES
#       - run: bundle exec rspec -- ${TESTFILES}
   #Start of Browser testing
   browsertest:
     machine: true
     resource_class: brianoh1979/brian-runner
     #parallelism: 4
     #Above runs the tests across four containers instead of one
     steps:
       - checkout
       - restore_cache:
          keys:
            - gem-cache-v1-{{ arch }}-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
            - gem-cache-v1-{{ arch }}-{{ .Branch }}
            - gem-cache-v1
 #      - run: apt-get update
       - run: bundle init
 #      - run:
 #         name: Install Cypress dependencies
 #         command: apt-get install xvfb libgtk-3-dev libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 --fix-missing
 #      - run:
 #         name: install cypress
 #         command: npm install cypress --save-dev
 #      - run: gem install bundler:2.0.1
       - run: bundle update --bundler
       - run:
           name: Boot rails server
           command: bin/rails s
           background: true
       - run: mkdir /tmp/results
       - run: npm install --save-dev mocha mochawesome mochawesome-merge mochawesome-report-generator
 #      - run: # open cypress and use sample_spec.js
 #         name: run
 #         command: $(npm bin)/cypress run -- --record --spec "cypress/integration/sample_spec.js" 
       
       - store_test_results:
           path: /tmp/results
       - store_artifacts:
           path: /tmp/results
           destination: results
   #Linters and static code analysis
   lintertest:
     machine: true
     resource_class: brianoh1979/brian-runner
     #parallelism: 4
     #Above runs the tests across four containers instead of one
     steps:
       - checkout
       - ruby-linter/rails_best_practices:
           paths: .
       - run:
            name: "Gem path envvars"
            command: |
              GEM_PATH=$GEM_HOME:$GEM_HOME/ruby/$RUBY_MAJOR.0
              PATH=$GEM_HOME/bin:$GEM_HOME/ruby/$RUBY_MAJOR.0/bin:$PATH
 #      - restore_cache:
 #         keys:
 #           - gem-cache-v1-{{ arch }}-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
 #           - gem-cache-v1-{{ arch }}-{{ .Branch }}
 #           - gem-cache-v1
  #     - run: gem install bundler:2.0.1
 #      - run: bundle init
 #      - run: bundle update --bundler
 #      - run: bundle exec bundle audit
  #     - run: bundle-audit check --ignore CVE-2015-7580 CVE-2015-7578 CVE-2015-7579
 #      - run: rails_best_practices .
   #Code Coverage
   codecoveragetest:
     machine: true
     resource_class: brianoh1979/brian-runner
     #parallelism: 4
     #Above runs the tests across four containers instead of one
     steps:
       - checkout
       - restore_cache:
          keys:
            - gem-cache-v1-{{ arch }}-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
            - gem-cache-v1-{{ arch }}-{{ .Branch }}
            - gem-cache-v1
  #     - run: gem install bundler:2.0.1
       - run: bundle init
       - run: bundle update --bundler
       - run: bundle install
       - run: rake db:test:prepare
       - run: rails test
       - store_artifacts: # for display in Artifacts: https://circleci.com/docs/2.0/artifacts/ 
          path: coverage
          prefix: coverage
    #Deploy job
   deploy:
     machine: true
     resource_class: brianoh1979/brian-runner
     #parallelism: 4
     #Above runs the tests across four containers instead of one
     steps:
       - checkout
       - restore_cache:
          keys:
            - gem-cache-v1-{{ arch }}-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
            - gem-cache-v1-{{ arch }}-{{ .Branch }}
            - gem-cache-v1
       - run:
           name: Deploy Develop to Heroku
           command: |
             git push --force https://heroku:$HEROKU_API_KEY2@git.heroku.com/thawing-cliffs-50633.git master

 workflows:
   version: 2
   build_and_test:
     jobs:
       - build
       - unittest:
           requires:
             - build
       - cypress/install:
           cache-key: >-
             cache-{{ arch }}-{{ .Branch }}-{{ checksum "frontend/package.json"
             }}
       - cypress/run:
           requires:
             - cypress/install
 #      - browsertest:
 #          requires:
 #            - build
       - lintertest:
           requires:
             - build
 #      - codecoveragetest:
 #          requires:
 #            - build
       - deploy:
           requires:
             - unittest
             - cypress/run
             - lintertest
 #            - codecoveragetest

